// Covers both FIFA codes (MEX, GER) and ISO alpha-3 codes (MEX, DEU)
// since football-data.org uses both depending on the endpoint.
const CODE_TO_ISO: Record<string, string> = {
  // FIFA codes
  AFG: "af", ALB: "al", ALG: "dz", AND: "ad", ANG: "ao",
  ARG: "ar", ARM: "am", AUS: "au", AUT: "at", AZE: "az",
  BAH: "bs", BAN: "bd", BEL: "be", BLR: "by", BLZ: "bz",
  BOL: "bo", BIH: "ba", BOT: "bw", BRA: "br", BUL: "bg",
  BFA: "bf", BDI: "bi", CAM: "kh", CAN: "ca", CPV: "cv",
  CHI: "cl", CHN: "cn", COL: "co", COM: "km", CGO: "cg",
  COD: "cd", CRC: "cr", CIV: "ci", CRO: "hr", CUB: "cu",
  ANT: "cw", CUW: "cw", CZE: "cz", DEN: "dk", ECU: "ec", EGY: "eg",
  ENG: "gb-eng", ESP: "es", ETH: "et", FIN: "fi", FIJ: "fj",
  FRA: "fr", GAB: "ga", GAM: "gm", GEO: "ge", GER: "de",
  GHA: "gh", GRE: "gr", GUA: "gt", GUI: "gn", GNB: "gw",
  HAI: "ht", HON: "hn", HUN: "hu", ISL: "is", IND: "in",
  IDN: "id", IRN: "ir", IRQ: "iq", IRL: "ie", ISR: "il",
  ITA: "it", JAM: "jm", JPN: "jp", JOR: "jo", KAZ: "kz",
  KEN: "ke", KOR: "kr", KSA: "sa", KUW: "kw", LIB: "lb",
  LBY: "ly", LIE: "li", LUX: "lu", MAD: "mg", MAR: "ma",
  MEX: "mx", MDA: "md", MNG: "mn", MOZ: "mz", MLI: "ml",
  MTN: "mr", NAM: "na", NED: "nl", NGA: "ng", NIR: "gb-nir",
  NOR: "no", NZL: "nz", OMA: "om", PAN: "pa", PAR: "py",
  PER: "pe", PHI: "ph", POL: "pl", POR: "pt", PRK: "kp",
  PUR: "pr", QAT: "qa", ROU: "ro", RSA: "za", RUS: "ru",
  RWA: "rw", SAL: "sv", SCO: "gb-sct", SEN: "sn", SLE: "sl",
  SVK: "sk", SVN: "si", SRB: "rs", SUI: "ch", SWE: "se",
  SYR: "sy", TAH: "pf", TAN: "tz", THA: "th", TRI: "tt",
  TUN: "tn", TUR: "tr", UGA: "ug", UKR: "ua", URU: "uy",
  USA: "us", UZB: "uz", VEN: "ve", VIE: "vn", WAL: "gb-wls",
  YEM: "ye", ZAM: "zm", ZIM: "zw",

  // ISO alpha-3 variants (football-data.org area.code uses these)
  AFR: "za", ALG: "dz", ARG: "ar", ARM: "am", AUS: "au",
  AUT: "at", AZE: "az", BEL: "be", BIH: "ba", BLR: "by",
  BOL: "bo", BRA: "br", CAN: "ca", CHE: "ch", CHL: "cl",
  CHN: "cn", COL: "co", CRI: "cr", CUW: "cw", CYP: "cy",
  CZE: "cz", DEU: "de", DNK: "dk", ECU: "ec", EGY: "eg",
  ESP: "es", ETH: "et", FIN: "fi", FJI: "fj", FRA: "fr",
  GAB: "ga", GBR: "gb", GEO: "ge", GHA: "gh", GRC: "gr",
  GTM: "gt", GIN: "gn", GNB: "gw", HTI: "ht", HND: "hn",
  HRV: "hr", HUN: "hu", IDN: "id", IND: "in", IRL: "ie",
  IRN: "ir", IRQ: "iq", ISL: "is", ISR: "il", ITA: "it",
  JAM: "jm", JOR: "jo", JPN: "jp", KAZ: "kz", KEN: "ke",
  KOR: "kr", KWT: "kw", LBN: "lb", LBY: "ly", LIE: "li",
  LUX: "lu", MAR: "ma", MCO: "mc", MDA: "md", MDG: "mg",
  MEX: "mx", MLI: "ml", MNE: "me", MNG: "mn", MOZ: "mz",
  MRT: "mr", MWI: "mw", MYS: "my", NAM: "na", NGA: "ng",
  NLD: "nl", NOR: "no", NZL: "nz", OMN: "om", PAN: "pa",
  PER: "pe", PHL: "ph", POL: "pl", PRT: "pt", PRK: "kp",
  PRY: "py", QAT: "qa", ROU: "ro", RUS: "ru", RWA: "rw",
  SAU: "sa", SDN: "sd", SEN: "sn", SLE: "sl", SLV: "sv",
  SRB: "rs", STP: "st", SVK: "sk", SVN: "si", SWE: "se",
  SYR: "sy", TAN: "tz", THA: "th", TTO: "tt", TUN: "tn",
  TUR: "tr", TZA: "tz", UGA: "ug", UKR: "ua", URY: "uy",
  USA: "us", UZB: "uz", VEN: "ve", VNM: "vn", YEM: "ye",
  ZAF: "za", ZMB: "zm", ZWE: "zw",
};

export function fifaToIso(code: string): string | null {
  return CODE_TO_ISO[code.toUpperCase()] ?? null;
}
